site_name: Yanis Kouidri's Docs
site_url: https://yanis-kouidri.github.io/personal-doc/
repo_url: https://github.com/yanis-kouidri/personal-doc
repo_name: yanis-kouidri/personal-doc
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Kubernetes: kubernetes.md
  - Git: git.md
  - Linux: linux.md
  - Network: network.md
  - Photos: photos.md
  - Videos: videos.md
  - Raspberry-Pi: raspberry-pi.md
  - Regex: regex.md
  - Windows 11: windows-11.md 
  - Bun: bun.md
  - PDF: pdf.md
  - Python: python.md

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: true